### ISSUE TITLE
Too strong assumption about $SC env variable in scionutil

### ISSUE THREAD

**Issue by mkowalski** [netsec-ethz/scion-apps#89] opened 2019-07-25 11:53 UTC
Currently the `imagefetcher` app assumes existence of the `$SC` env variable pointing to the directory containing `/gen/ia`. This means it must always be run from the context of `scion` user, what in the scope of automated infrastructure monitoring is not desired.

If access to `/gen/ia` is required, the app should be able to consume it e.g. as a command line parameter, but not assume the `$SC` env variable will be present.

**Comment by chaehni** [comment] 2019-08-22 09:18
As far as I'm concerned `$SC/gen/ia` is only read for convenience when users run their AS in a SCIONLab context to get the local address. Imagefetcher can be run by providing the local address explicitly instead. (provide `-c` flag)

**Comment by juagargi** [comment] 2019-09-30 08:56
I'm renaming the issue to be generic enough, as it affects the util library, etc.
Since packaging, the standard SCIONLab machines don't have a `$SC` variable, and the code in scionutil would fail.
The library should look for the `ia` file in `/etc/scion/gen` first, and then fallback to `$SC` if not found there.
A quick `git grep -n 'Getenv("SC")'` shows only two cases in `lib/scionutil` and one in `tools/pathdb_dump`

**Comment by mkowalski** [comment] 2019-09-30 09:43
> The library should look for the `ia` file in `/etc/scion/gen` first, and then fallback to `$SC` if not found there.
Just to be clear here, the library should accept location of the gen/ folder as an argument/parameter, otherwise we are just renaming the problem from hardcoding one variable into hardcoding another variable

**Comment by matzf** [comment] 2019-09-30 14:53
I have a stronger opinion here; the library should NOT read the `ia` file at all.

**Comment by juagargi** [comment] 2019-10-01 15:32
We can try to guess the IA from the `gen` sub directory structure. This is not much better than relying on the `ia` file though.
It would be nice to have a feature in `sciond` or the dispatcher that would return the local IA, but if we want to be able to obtain the IA of the machine (or IAs) before initializing `sciond`, we'd have to rely only on the dispatcher, or use a different approach.
Having a `localhost` entry in `/etc/hosts` is not a bad idea though.

**Comment by matzf** [comment] 2019-10-02 06:35
>  It would be nice to have a feature in sciond or the dispatcher that would return the local IA, but if we want to be able to obtain the IA of the machine (or IAs) before initializing sciond, we'd have to rely only on the dispatcher, or use a different approach.

The feature is there (in sciond), we'd just have to make use of it. Before my vacation I had started to to implement this directly as the default `Init` in `snet`. It would be easy to do just this in the scion-apps `lib` initialisation. I'll create a PR, hopefully today.

**Comment by juagargi** [comment] 2019-10-02 07:11
Then the problem will be how to get the `sciond` socket filename in the first place. I.e. we'd like to have the applications connect to SCION using "the" AS the computer belongs to, without specifying anything. In case of more than one `sciond` running, then just one of them. Maybe we can just connect to the first of `ls /run/shm/sciond/*.sock` ?

**Comment by matzf** [comment] 2019-10-02 07:20
Sure, but that doesn't seem to tricky. To me it seems like the obvious approach/expected behaviour would be:
- if there is a single socket, just use it
- if there are multiple, ask the user to specify one (either with a local IA and sciondFromIA of with a path)

**Comment by matzf** [comment] 2020-01-23 17:00
Fixed in #119

**Closed by matzf** 2020-01-23 17:00 UTC
Labels: bug
